# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ipix', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='photos_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
